### PR TITLE
Implement update platform details endpoint

### LINKED ISSUE #36: Implement Update platform details endpoint
**Description:**
This issue involves implementing an API to update platform details. The endpoint should allow Admin to make a PUT request to `{{baseUrl}}/api/admin/platform`.

**Tasks:**
1. Create a controller for the `/controllers/platform` endpoint in the backend (create the route platform if not created).
2. Parse and validate the request body to ensure it matches the expected format.
3. Implement appropriate error handling and response status codes for different scenarios (e.g., validation errors, database errors).
5. Write unit tests to validate the functionality and correctness of the endpoint.

API documentation: https://documenter.getpostman.com/view/27421496/2s93m1a4ac#8744a3ee-970f-489a-853d-8b23fdee8de3

ER diagram: https://drive.google.com/file/d/11KMgdNu2mSAm0Ner8UsSPQpZJS8QNqYc/view 

**Acceptance Criteria:**
- The profile API endpoint `/controllers/platfrom` is implemented via a PUT request.
- The request body is properly parsed and validated for the required format.
- Appropriate error handling is implemented, providing meaningful error messages and correct response status codes.
- Unit tests are written to validate the functionality and correctness of the endpoint.

**Additional Information:**
No

**Related Dependencies or References:**
No

### PR DESCRIPTION
**Pull request by Madhawa97**
## Purpose

The purpose of this PR is to fix #36 

## Goals
The endpoint should allow Admin to update the platform details.

## Approach
Utilized the existing `/api/admin/platform` endpoint to handle a `PUT` request with a body of the updated platform. Implemented the rrror handing with status codes and also the unit tests are written.

Response for update request: 
```json
{
  "platform": {
    "description": "This is a updated description.",
    "mentor_questions": [
      {
        "question": "What are your career goals?",
        "question_type": "text",
        "options": []
      },
      {
        "question": "How do you handle challenges?",
        "question_type": "text",
        "options": []
      },
      {
        "question": "Tell me about a time when you demonstrated leadership skills.",
        "question_type": "text",
        "options": []
      }
    ],
    "image_url": "https://example.com/images/sample.jpg",
    "landing_page_url": "https://example.com/landing-page",
    "email_templates": {
      "template1": {
        "subject": "Welcome to our mentoring program!",
        "body": "Dear {{mentor_name}},\n\nWe are excited to have you join our mentoring program..."
      },
      "template2": {
        "subject": "Follow-up on your mentoring session",
        "body": "Dear {{mentee_name}},\n\nI wanted to follow up on our recent mentoring session..."
      }
    },
    "title": "Sample Mentoring Program",
    "uuid": "89a1c2a6-8c39-420e-8274-a1719b1667c1",
    "created_at": "2023-10-27T10:26:10.652Z",
    "updated_at": "2023-10-27T10:26:10.652Z"
  },
  "message": "Platform updated successfully"
}
```

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by anjula-sack — CHANGES_REQUESTED** [review]
@Madhawa97 The tests are failing. Can you check?

**Comment by Madhawa97** [comment]
Surely will check in 3 hours. This is probably due to the entity level changes.

**Comment by Madhawa97** [comment]
@anjula-sack The issue seems to have been sorted. All tests passed in the local env.

**Review by anjula-sack — APPROVED** [review]
Thank you! @Madhawa97

**Pull request merged**
